In [32]:
import pandas as pd

# Loading the Online CSV file without the sheet_name argument
online_data = pd.read_csv('/Users/farahfatima/Downloads/Marketing_AM_Assignment 2/web_events_item_brand.csv')

# Displaying the first few rows to verify the structure of the online data
online_data.head()

/var/folders/vx/qtvwr5n55l701vv3rh9p4ztw0000gn/T/ipykernel_5628/4104884061.py:4: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  online_data = pd.read_csv('/Users/farahfatima/Downloads/Marketing_AM_Assignment 2/web_events_item_brand.csv')

,Unnamed: 0,event_date,event_timestamp,event_name,user_pseudo_id,user_id,session_id,items
0,0,20220217,1645027202983913,page_view,1.464167e+09,NaN,1645027104,NaN
1,1,20220217,1645027203907519,page_view,2.756993e+08,135740.0,1645027172,NaN
2,2,20220217,1645027205739210,page_view,1.927853e+09,NaN,1645026645,NaN
3,3,20220217,1645027207452562,page_view,1.791794e+09,NaN,1645027206,NaN
4,4,20220217,1645027210818886,page_view,4.099262e+08,NaN,1645027202,NaN

In [33]:
# Filtering online data for "purchase" events
online_purchase_data = online_data[online_data['event_name'] == 'purchase'].copy()

# Displaying the first few rows to confirm filtering for purchase events
online_purchase_data.head()

,Unnamed: 0,event_date,event_timestamp,event_name,user_pseudo_id,user_id,session_id,items
272010,28,20220221,1645377058255171,purchase,1.066863e+08,135997.0,1645376764,"[{'item_id': '50440514-VL4005', 'item_brand': ..."
280566,78,20220221,1645412583293754,purchase,1.424286e+09,135998.0,1645412292,"[{'item_id': '50850023', 'item_brand': 'Others..."
283997,102,20220221,1645415691466375,purchase,1.064509e+09,136000.0,1645415451,"[{'item_id': 'PB-LR0173', 'item_brand': 'D', '..."
288925,119,20220221,1645421203751729,purchase,1.708116e+09,136002.0,1645420778,"[{'item_id': '40210001-TP', 'item_brand': 'AM'..."
292136,359,20220221,1645424161050913,purchase,1.908221e+08,136008.0,1645423716,"[{'item_id': '52460052', 'item_brand': 'Others..."

In [34]:
# Define a function to safely split the items list into separate columns for each item_id, price, and quantity
import json

def split_items_safe(data):
    # Initialize dictionaries to hold the new columns
    item_ids = {}
    prices = {}
    quantities = {}
    
    # Loop over each row in the data
    for index, row in data.iterrows():
        # Parse the items column
        items = row['items']
        try:
            if isinstance(items, str):  # If items are strings (e.g., from JSON structure), parse them
                items = json.loads(items.replace("'", "\""))
        except json.JSONDecodeError:
            # Skip rows with parsing errors
            continue

        # Loop over each item and add it to the dictionaries
        for i, item in enumerate(items, start=1):
            item_ids[f'Item{i}_id'] = item.get('item_id', None)
            prices[f'Item{i}_price'] = item.get('price', None)
            quantities[f'Item{i}_quantity'] = item.get('quantity', None)
        
        # Update the row with new columns
        for key, value in item_ids.items():
            data.loc[index, key] = value
        for key, value in prices.items():
            data.loc[index, key] = value
        for key, value in quantities.items():
            data.loc[index, key] = value

    return data

# Applying the transformation function to the online purchase data
online_transformed = split_items_safe(online_purchase_data.copy())

# Displaying the transformed online data to confirm the results
online_transformed.head()

,Unnamed: 0,event_date,event_timestamp,event_name,user_pseudo_id,user_id,session_id,items,Item1_id,Item1_price,...,Item5_quantity,Item6_quantity,Item7_quantity,Item8_quantity,Item9_quantity,Item10_quantity,Item11_quantity,Item12_quantity,Item13_quantity,Item14_quantity
272010,28,20220221,1645377058255171,purchase,1.066863e+08,135997.0,1645376764,"[{'item_id': '50440514-VL4005', 'item_brand': ...",50440514-VL4005,466.360000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
280566,78,20220221,1645412583293754,purchase,1.424286e+09,135998.0,1645412292,"[{'item_id': '50850023', 'item_brand': 'Others...",50850023,428.970000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
283997,102,20220221,1645415691466375,purchase,1.064509e+09,136000.0,1645415451,"[{'item_id': 'PB-LR0173', 'item_brand': 'D', '...",PB-LR0173,1335.510000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
288925,119,20220221,1645421203751729,purchase,1.708116e+09,136002.0,1645420778,"[{'item_id': '40210001-TP', 'item_brand': 'AM'...",40210001-TP,1027.099999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292136,359,20220221,1645424161050913,purchase,1.908221e+08,136008.0,1645423716,"[{'item_id': '52460052', 'item_brand': 'Others...",52460052,428.970000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
# Ensuring the metrics calculation is strictly for "purchase" events in the online data

# Filtering online data again for "purchase" events only to avoid any errors
online_purchase_data = online_data[online_data['event_name'] == 'purchase'].copy()

# Function to accurately calculate total sales value and items sold from 'items' column
def calculate_sales_metrics(data):
    total_sales_value = 0
    total_items_sold = 0
    for index, row in data.iterrows():
        try:
            items = json.loads(row['items'].replace("'", "\""))  # Parse items
            for item in items:
                price = item.get('price', 0)
                quantity = item.get('quantity', 1)  # Default quantity to 1 if missing
                total_sales_value += price * quantity
                total_items_sold += quantity
        except (json.JSONDecodeError, TypeError):
            continue  # Skip rows with errors in 'items' format
    return total_sales_value, total_items_sold

# Recalculating metrics based on purchases only in the online data
total_sales_value_online, total_items_sold_online = calculate_sales_metrics(online_purchase_data)

# Calculating average transaction value and average items per purchase
total_transactions_online = online_purchase_data['user_id'].nunique()
average_transaction_value_online = total_sales_value_online / total_transactions_online
average_items_per_purchase_online = total_items_sold_online / total_transactions_online

# Displaying the final results
total_sales_value_online, total_items_sold_online, average_transaction_value_online, average_items_per_purchase_online

(180902.21998500003, 296, 1144.9507593987344, 1.8734177215189873)

In [36]:
# Filtering online data for "purchase" events only, ensuring focus on the relevant data subset
online_purchase_data = online_data[online_data['event_name'] == 'purchase'].copy()

# Converting event_date to datetime for easier analysis
online_purchase_data['event_date'] = pd.to_datetime(online_purchase_data['event_date'], format='%Y%m%d')

# Function to calculate daily sales and quantity for online purchase data
def calculate_daily_metrics(data):
    # Calculate total quantity sold per day
    daily_quantity = data.groupby('event_date')['quantity'].sum()
    
    # Find the date with the highest quantity purchased
    highest_daily_quantity = daily_quantity.max()
    highest_daily_quantity_date = daily_quantity.idxmax()

    # Calculate total sales value per day
    daily_sales = data.groupby('event_date').apply(lambda x: sum(json.loads(x['items'].replace("'", "\""))[0]['price'] * json.loads(x['items'].replace("'", "\""))[0].get('quantity', 1) for i, x in enumerate(x.iterrows())))

In [37]:
# Updated code without references to 'pageviews' and 'users'

# Function to calculate daily sales and quantity metrics for online purchase data
def calculate_daily_metrics_no_pageviews(data):
    daily_quantity = {}
    daily_sales = {}

    for index, row in data.iterrows():
        try:
            items = json.loads(row['items'].replace("'", "\""))  # Parse items
            date = row['event_date']
            if date not in daily_quantity:
                daily_quantity[date] = 0
                daily_sales[date] = 0
            for item in items:
                price = item.get('price', 0)
                quantity = item.get('quantity', 1)
                daily_quantity[date] += quantity
                daily_sales[date] += price * quantity
        except (json.JSONDecodeError, TypeError):
            continue

    return pd.Series(daily_quantity), pd.Series(daily_sales)

# Applying the function to get daily metrics
daily_quantity, daily_sales = calculate_daily_metrics_no_pageviews(online_purchase_data)

# Highest daily quantity purchased
highest_daily_quantity = daily_quantity.max()
highest_daily_quantity_date = daily_quantity.idxmax()

# Highest daily revenue
highest_daily_revenue = daily_sales.max()
highest_daily_revenue_date = daily_sales.idxmax()

# Weekly metrics calculation
weekly_orders = online_purchase_data['event_date'].dt.isocalendar().week.nunique()
average_weekly_orders = len(online_purchase_data['user_id'].unique()) / weekly_orders
average_weekly_items = daily_quantity.sum() / weekly_orders

# Displaying the results
highest_daily_quantity, highest_daily_quantity_date, average_weekly_orders, average_weekly_items, highest_daily_revenue, highest_daily_revenue_date

(58,
 Timestamp('2022-02-27 00:00:00'),
 158.0,
 296.0,
 41536.42999499999,
 Timestamp('2022-02-27 00:00:00'))

In [38]:
# Removing the most active date calculation as 'pageviews' and 'users' columns are not present

# Displaying results for highest daily quantity, highest daily revenue, and weekly averages only

# Highest daily quantity purchased
highest_daily_quantity = daily_quantity.max()
highest_daily_quantity_date = daily_quantity.idxmax()

# Highest daily revenue
highest_daily_revenue = daily_sales.max()
highest_daily_revenue_date = daily_sales.idxmax()

# Weekly metrics calculation
weekly_orders = online_purchase_data['event_date'].dt.isocalendar().week.nunique()
average_weekly_orders = len(online_purchase_data['user_id'].unique()) / weekly_orders
average_weekly_items = daily_quantity.sum() / weekly_orders

# Displaying the results
highest_daily_quantity, highest_daily_quantity_date, average_weekly_orders, average_weekly_items, highest_daily_revenue, highest_daily_revenue_date

(58,
 Timestamp('2022-02-27 00:00:00'),
 158.0,
 296.0,
 41536.42999499999,
 Timestamp('2022-02-27 00:00:00'))

In [6]:
import pandas as pd
import json
import numpy as np

# Load the online data
online_data = pd.read_csv('/Users/farahfatima/Downloads/Marketing_AM_Assignment 2/web_events_item_brand.csv')

# Filter for 'purchase' events
online_purchase_data = online_data[online_data['event_name'] == 'purchase'].copy()

# Define a function to split items into individual columns for each item_id, price, and quantity
def split_items_safe(data):
    # Initialize dictionaries to hold the new columns
    item_ids = {}
    prices = {}
    quantities = {}
    
    # Loop over each row in the data
    for index, row in data.iterrows():
        items = row['items']
        try:
            if isinstance(items, str):  # Parse JSON if items are strings
                items = json.loads(items.replace("'", "\""))
        except json.JSONDecodeError:
            continue  # Skip rows with errors in parsing
        
        # Loop through each item in the items list
        for i, item in enumerate(items, start=1):
            item_ids[f'Item{i}_id'] = item.get('item_id', None)
            prices[f'Item{i}_price'] = item.get('price', None)
            quantities[f'Item{i}_quantity'] = item.get('quantity', None)
        
        # Update the row with new columns
        for key, value in item_ids.items():
            data.loc[index, key] = value
        for key, value in prices.items():
            data.loc[index, key] = value
        for key, value in quantities.items():
            data.loc[index, key] = value

    return data

# Transform the purchase data to split items
online_transformed = split_items_safe(online_purchase_data.copy())

# Calculate total sales value and total items sold
def calculate_sales_metrics(data):
    total_sales_value = 0
    total_items_sold = 0
    for index, row in data.iterrows():
        try:
            items = json.loads(row['items'].replace("'", "\""))  # Parse items
            for item in items:
                price = item.get('price', 0)
                quantity = item.get('quantity', 1)
                total_sales_value += price * quantity
                total_items_sold += quantity
        except (json.JSONDecodeError, TypeError):
            continue  # Skip rows with errors
    return total_sales_value, total_items_sold

# Calculate metrics based on transformed data
total_sales_value_online, total_items_sold_online = calculate_sales_metrics(online_transformed)

# Calculate average transaction value and items per purchase
total_transactions_online = online_purchase_data['user_id'].nunique()
average_transaction_value_online = total_sales_value_online / total_transactions_online
average_items_per_purchase_online = total_items_sold_online / total_transactions_online

# Calculate the exact average price per item
average_price = total_sales_value_online / total_items_sold_online if total_items_sold_online > 0 else 0

# Define price bins and calculate total revenue per price bucket
price_bins = [0, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 2000, 3000]
all_prices = [item for sublist in online_transformed.filter(regex='Item.*_price').values.tolist() for item in sublist if item is not None]
price_series = pd.Series(all_prices)
online_purchase_data['price_bucket'] = pd.cut(price_series, bins=price_bins)

# Aggregate to get total revenue per price bucket
price_bucket_analysis = online_purchase_data.groupby('price_bucket').apply(
    lambda x: sum([p for p in all_prices if p in x['price_bucket'].values])
).reset_index(name='total_revenue')

# Identify optimal price points with higher than average revenue
average_revenue = price_bucket_analysis['total_revenue'].mean()
optimal_price_buckets = price_bucket_analysis[price_bucket_analysis['total_revenue'] > average_revenue]

# Display results
print(f"Exact Average Price for Purchases: ${average_price:.2f}")
print("Optimal Price Points (Buckets with Higher Revenue):")
print(optimal_price_buckets[['price_bucket', 'total_revenue']])

# Display transaction metrics
print("Total Sales Value:", total_sales_value_online)
print("Total Items Sold:", total_items_sold_online)
print("Average Transaction Value:", average_transaction_value_online)
print("Average Items per Purchase:", average_items_per_purchase_online)

/var/folders/vx/qtvwr5n55l701vv3rh9p4ztw0000gn/T/ipykernel_9081/3805881002.py:6: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  online_data = pd.read_csv('/Users/farahfatima/Downloads/Marketing_AM_Assignment 2/web_events_item_brand.csv')

Exact Average Price for Purchases: $611.16
Optimal Price Points (Buckets with Higher Revenue):
Empty DataFrame
Columns: [price_bucket, total_revenue]
Index: []
Total Sales Value: 180902.21998500003
Total Items Sold: 296
Average Transaction Value: 1144.9507593987344
Average Items per Purchase: 1.8734177215189873

In [16]:
import pandas as pd
import json

# Load the online data and filter for 'purchase' events
online_data = pd.read_csv('/Users/farahfatima/Downloads/Marketing_AM_Assignment 2/web_events_item_brand.csv', low_memory=False)
online_purchase_data = online_data[online_data['event_name'] == 'purchase'].copy()

# Step 1: Parse the 'items' JSON data and extract individual item prices and quantities
def extract_prices_and_quantities(data):
    total_sales_value = 0
    total_items_sold = 0
    prices = []
    
    for _, row in data.iterrows():
        try:
            items = json.loads(row['items'].replace("'", "\""))  # Parse items as JSON
            for item in items:
                price = item.get('price', 0)
                quantity = item.get('quantity', 1)
                total_sales_value += price * quantity
                total_items_sold += quantity
                prices.extend([price] * quantity)  # Include each price multiple times based on quantity
        except (json.JSONDecodeError, TypeError):
            continue  # Skip rows with errors in 'items' format
    
    average_price = total_sales_value / total_items_sold if total_items_sold > 0 else 0
    return average_price, prices

# Calculate the average price and extract a list of all prices
average_price, all_prices = extract_prices_and_quantities(online_purchase_data)

# Step 2: Define price buckets for sensitivity analysis
price_bins = [0, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1500, 2000, 3000, 4000]
price_bucket_series = pd.cut(all_prices, bins=price_bins)
price_bucket_df = pd.DataFrame({'price': all_prices, 'price_bucket': price_bucket_series})

# Step 3: Calculate total revenue for each price bucket
price_bucket_analysis = price_bucket_df.groupby('price_bucket').agg(total_revenue=('price', 'sum')).reset_index()

# Step 4: Calculate the average revenue across all price buckets
average_revenue = price_bucket_analysis['total_revenue'].mean()

# Step 5: Identify buckets with higher-than-average revenue
optimal_price_buckets = price_bucket_analysis[price_bucket_analysis['total_revenue'] > average_revenue]

# Display the results
print(f"Average Price: ${average_price:.2f}")
print("Optimal Price Points (Buckets with Higher Revenue):")
print(optimal_price_buckets[['price_bucket', 'total_revenue']])

Average Price: $611.16
Optimal Price Points (Buckets with Higher Revenue):
    price_bucket  total_revenue
4     (400, 500]   16301.890000
8     (800, 900]   27875.790000
10  (1000, 1500]   73036.429986
11  (1500, 2000]   13291.600000

In [17]:
import pandas as pd
import json

# Load the online data and filter for 'purchase' events
online_data = pd.read_csv('/Users/farahfatima/Downloads/Marketing_AM_Assignment 2/web_events_item_brand.csv')
online_purchase_data = online_data[online_data['event_name'] == 'purchase'].copy()

# Function to safely parse items, calculate revenue, and quantity sold in each price bucket
def calculate_metrics(data):
    total_sales_value = 0
    total_items_sold = 0
    prices = []
    quantities = []

    for index, row in data.iterrows():
        try:
            items = json.loads(row['items'].replace("'", "\""))
            for item in items:
                price = item.get('price', 0)
                quantity = item.get('quantity', 1)
                total_sales_value += price * quantity
                total_items_sold += quantity
                prices.append(price)
                quantities.append(quantity)
        except json.JSONDecodeError:
            continue

    return total_sales_value, total_items_sold, prices, quantities

# Calculate total sales, items sold, and gather all prices and quantities
total_sales_value, total_items_sold, prices, quantities = calculate_metrics(online_purchase_data)

# Define price buckets for analysis and add total quantity for each bucket
price_bins = [0, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1500, 2000, 3000, 4000]
online_purchase_data['price_bucket'] = pd.cut(pd.Series(prices), bins=price_bins)

# Create a DataFrame to calculate revenue and quantity per price bucket
bucket_data = pd.DataFrame({
    'price': prices,
    'quantity': quantities,
    'price_bucket': pd.cut(pd.Series(prices), bins=price_bins)
})

# Aggregate revenue and quantity for each price bucket
price_bucket_analysis = bucket_data.groupby('price_bucket').agg(
    total_revenue=('price', lambda x: (x * bucket_data.loc[x.index, 'quantity']).sum()),
    total_quantity=('quantity', 'sum')
).reset_index()

# Filter for top revenue-generating buckets
average_revenue = price_bucket_analysis['total_revenue'].mean()
top_buckets = price_bucket_analysis[price_bucket_analysis['total_revenue'] > average_revenue]

# Display results
print("Top Revenue-Generating Price Buckets with Quantities:")
print(top_buckets[['price_bucket', 'total_revenue', 'total_quantity']])

Top Revenue-Generating Price Buckets with Quantities:
    price_bucket  total_revenue  total_quantity
4     (400, 500]   16301.890000              37
8     (800, 900]   27875.790000              33
10  (1000, 1500]   73036.429986              61
11  (1500, 2000]   13291.600000               8

/var/folders/vx/qtvwr5n55l701vv3rh9p4ztw0000gn/T/ipykernel_9081/4037192520.py:5: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  online_data = pd.read_csv('/Users/farahfatima/Downloads/Marketing_AM_Assignment 2/web_events_item_brand.csv')

In [18]:
import pandas as pd
import json

# Load the data and filter for 'purchase' events
online_data = pd.read_csv('/Users/farahfatima/Downloads/Marketing_AM_Assignment 2/web_events_item_brand.csv')
online_purchase_data = online_data[online_data['event_name'] == 'purchase'].copy()

# Define a function to parse items and calculate sales per brand
def calculate_brand_metrics(data):
    brand_sales = {}
    brand_quantity = {}

    for index, row in data.iterrows():
        try:
            items = json.loads(row['items'].replace("'", "\""))
            for item in items:
                brand = item.get('item_brand', 'Others')
                price = item.get('price', 0)
                quantity = item.get('quantity', 1)

                # Update sales and quantity for each brand
                if brand in brand_sales:
                    brand_sales[brand] += price * quantity
                    brand_quantity[brand] += quantity
                else:
                    brand_sales[brand] = price * quantity
                    brand_quantity[brand] = quantity
        except json.JSONDecodeError:
            continue

    # Convert to DataFrame
    brand_df = pd.DataFrame({
        'Brand': list(brand_sales.keys()),
        'Total_Sales_Value': list(brand_sales.values()),
        'Items_Sold': list(brand_quantity.values())
    })

    # Calculate Market Share
    total_sales = brand_df['Total_Sales_Value'].sum()
    brand_df['Market_Share'] = (brand_df['Total_Sales_Value'] / total_sales) * 100

    # Sort by Total Sales Value
    brand_df = brand_df.sort_values(by='Total_Sales_Value', ascending=False).reset_index(drop=True)
    
    return brand_df

# Run the analysis
brand_analysis_df = calculate_brand_metrics(online_purchase_data)

# Display top 5 brands and "Others" category
top_5_brands = brand_analysis_df.head(5)
others_market_share = brand_analysis_df[brand_analysis_df['Brand'] == 'Others']['Market_Share'].values[0]
total_market_share_top_5 = top_5_brands['Market_Share'].sum()

# Display results
print("Top 5 Brands Analysis:")
print(top_5_brands)
print(f"Top 5 brands control {total_market_share_top_5:.2f}% of online sales.")
print(f"'Others' category has a market share of {others_market_share:.2f}%, suggesting potential for brand expansion.")

Top 5 Brands Analysis:
    Brand  Total_Sales_Value  Items_Sold  Market_Share
0  Others       44499.110000          95     24.598432
1       E       20577.579999          32     11.374974
2       P       17180.379997          17      9.497053
3       D       15977.560000          14      8.832153
4       S       12898.130000           9      7.129890
Top 5 brands control 61.43% of online sales.
'Others' category has a market share of 24.60%, suggesting potential for brand expansion.

/var/folders/vx/qtvwr5n55l701vv3rh9p4ztw0000gn/T/ipykernel_9081/3933133558.py:5: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  online_data = pd.read_csv('/Users/farahfatima/Downloads/Marketing_AM_Assignment 2/web_events_item_brand.csv')

In [21]:
import pandas as pd

# Load the online data
online_data = pd.read_csv('/Users/farahfatima/Downloads/Marketing_AM_Assignment 2/web_events_item_brand.csv')

# Step 1: Define each funnel stage
pageviews = online_data[online_data['event_name'] == 'pageview'].shape[0]
add_to_cart = online_data[online_data['event_name'] == 'add_to_cart'].shape[0]
begin_checkout = online_data[online_data['event_name'] == 'begin_checkout'].shape[0]
purchases = online_data[online_data['event_name'] == 'purchase'].shape[0]

# Step 2: Calculate conversion percentages between stages
conversion_add_to_cart = (add_to_cart / pageviews) * 100 if pageviews > 0 else 0
conversion_begin_checkout = (begin_checkout / add_to_cart) * 100 if add_to_cart > 0 else 0
conversion_purchases = (purchases / begin_checkout) * 100 if begin_checkout > 0 else 0

# Step 3: Summarize the results in a table format
funnel_analysis = pd.DataFrame({
    'Stage': ['Pageviews', 'Add to Cart', 'Begin Checkout', 'Purchases'],
    'Absolute Number': [pageviews, add_to_cart, begin_checkout, purchases],
    'Conversion % from Previous Stage': [None, f"{conversion_add_to_cart:.2f}%", f"{conversion_begin_checkout:.2f}%", f"{conversion_purchases:.2f}%"]
})

# Display the funnel analysis
print("Conversion Funnel Analysis:\n")
print(funnel_analysis)

# Step 4: Additional metrics
add_to_cart_rate = (add_to_cart / pageviews) * 100 if pageviews > 0 else 0
checkout_rate = (begin_checkout / add_to_cart) * 100 if add_to_cart > 0 else 0
purchase_rate = (purchases / begin_checkout) * 100 if begin_checkout > 0 else 0

print("\nAdditional Funnel Metrics:")
print(f"• Add to Cart Rate: {add_to_cart_rate:.2f}% of users add items to cart")
print(f"• Checkout Rate: {checkout_rate:.2f}% of cart additions proceed to checkout")
print(f"• Purchase Rate: {purchase_rate:.2f}% of checkouts convert to purchase")

# Step 5: Key insights (optional, manually interpret based on output)

/var/folders/vx/qtvwr5n55l701vv3rh9p4ztw0000gn/T/ipykernel_9081/26405990.py:4: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  online_data = pd.read_csv('/Users/farahfatima/Downloads/Marketing_AM_Assignment 2/web_events_item_brand.csv')

Conversion Funnel Analysis:

            Stage  Absolute Number Conversion % from Previous Stage
0       Pageviews                0                             None
1     Add to Cart            19063                            0.00%
2  Begin Checkout             1177                            6.17%
3       Purchases              161                           13.68%

Additional Funnel Metrics:
• Add to Cart Rate: 0.00% of users add items to cart
• Checkout Rate: 6.17% of cart additions proceed to checkout
• Purchase Rate: 13.68% of checkouts convert to purchase